//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourDO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JohnnyInputStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JohnnyInputStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FourDO.Resources.JohnnyInputStrings", typeof(JohnnyInputStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Set.
        /// </summary>
        internal static string AddSet {
            get {
                return ResourceManager.GetString("AddSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis.
        /// </summary>
        internal static string Axis {
            get {
                return ResourceManager.GetString("Axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding Set.
        /// </summary>
        internal static string BindingSet {
            get {
                return ResourceManager.GetString("BindingSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        internal static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string ButtonA {
            get {
                return ResourceManager.GetString("ButtonA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string ButtonB {
            get {
                return ResourceManager.GetString("ButtonB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string ButtonC {
            get {
                return ResourceManager.GetString("ButtonC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance by a Single Frame.
        /// </summary>
        internal static string ButtonConsoleAdvanceFrame {
            get {
                return ResourceManager.GetString("ButtonConsoleAdvanceFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        internal static string ButtonConsoleFullScreen {
            get {
                return ResourceManager.GetString("ButtonConsoleFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load State.
        /// </summary>
        internal static string ButtonConsoleLoadState {
            get {
                return ResourceManager.GetString("ButtonConsoleLoadState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string ButtonConsolePause {
            get {
                return ResourceManager.GetString("ButtonConsolePause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string ButtonConsoleReset {
            get {
                return ResourceManager.GetString("ButtonConsoleReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save State.
        /// </summary>
        internal static string ButtonConsoleSaveState {
            get {
                return ResourceManager.GetString("ButtonConsoleSaveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot.
        /// </summary>
        internal static string ButtonConsoleScreenshot {
            get {
                return ResourceManager.GetString("ButtonConsoleScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save State Slot : Next.
        /// </summary>
        internal static string ButtonConsoleStateSlotNext {
            get {
                return ResourceManager.GetString("ButtonConsoleStateSlotNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save State Slot : Previous.
        /// </summary>
        internal static string ButtonConsoleStateSlotPrevious {
            get {
                return ResourceManager.GetString("ButtonConsoleStateSlotPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string ButtonDown {
            get {
                return ResourceManager.GetString("ButtonDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L (Left Shoulder).
        /// </summary>
        internal static string ButtonL {
            get {
                return ResourceManager.GetString("ButtonL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string ButtonLeft {
            get {
                return ResourceManager.GetString("ButtonLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P (&quot;Play/Pause&quot;).
        /// </summary>
        internal static string ButtonP {
            get {
                return ResourceManager.GetString("ButtonP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R (Right Shoulder).
        /// </summary>
        internal static string ButtonR {
            get {
                return ResourceManager.GetString("ButtonR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string ButtonRight {
            get {
                return ResourceManager.GetString("ButtonRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string ButtonUp {
            get {
                return ResourceManager.GetString("ButtonUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X (&quot;Stop&quot;).
        /// </summary>
        internal static string ButtonX {
            get {
                return ResourceManager.GetString("ButtonX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        internal static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        internal static string Console {
            get {
                return ResourceManager.GetString("Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        internal static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Devices:.
        /// </summary>
        internal static string CurrentDevices {
            get {
                return ResourceManager.GetString("CurrentDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Set.
        /// </summary>
        internal static string DeleteSet {
            get {
                return ResourceManager.GetString("DeleteSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear a binding.
        /// </summary>
        internal static string InfoClearABinding {
            get {
                return ResourceManager.GetString("InfoClearABinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete, Backspace.
        /// </summary>
        internal static string InfoClearKeys {
            get {
                return ResourceManager.GetString("InfoClearKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected devices:.
        /// </summary>
        internal static string InfoDetectedDevices {
            get {
                return ResourceManager.GetString("InfoDetectedDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to device.
        /// </summary>
        internal static string InfoDevice {
            get {
                return ResourceManager.GetString("InfoDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to devices.
        /// </summary>
        internal static string InfoDevices {
            get {
                return ResourceManager.GetString("InfoDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Also, use escape to cancel setting a binding).
        /// </summary>
        internal static string InfoEscapeToCancel {
            get {
                return ResourceManager.GetString("InfoEscapeToCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move mouse here to view devices.
        /// </summary>
        internal static string InfoMoveMouse {
            get {
                return ResourceManager.GetString("InfoMoveMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no devices.
        /// </summary>
        internal static string InfoNoDevices {
            get {
                return ResourceManager.GetString("InfoNoDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a binding.
        /// </summary>
        internal static string InfoSetABinding {
            get {
                return ResourceManager.GetString("InfoSetABinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Click, Space, Enter.
        /// </summary>
        internal static string InfoSetKeys {
            get {
                return ResourceManager.GetString("InfoSetKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with.
        /// </summary>
        internal static string InfoWith {
            get {
                return ResourceManager.GetString("InfoWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to joy.
        /// </summary>
        internal static string JoyAbbreviated {
            get {
                return ResourceManager.GetString("JoyAbbreviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick.
        /// </summary>
        internal static string Joystick {
            get {
                return ResourceManager.GetString("Joystick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        internal static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (listening...).
        /// </summary>
        internal static string Listening {
            get {
                return ResourceManager.GetString("Listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoV.
        /// </summary>
        internal static string PointOfViewAbbreviated {
            get {
                return ResourceManager.GetString("PointOfViewAbbreviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Button.
        /// </summary>
        internal static string PreviewAButton {
            get {
                return ResourceManager.GetString("PreviewAButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B Button.
        /// </summary>
        internal static string PreviewBButton {
            get {
                return ResourceManager.GetString("PreviewBButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C Button.
        /// </summary>
        internal static string PreviewCButton {
            get {
                return ResourceManager.GetString("PreviewCButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down (&quot;Seek Backwards&quot;).
        /// </summary>
        internal static string PreviewDownButton {
            get {
                return ResourceManager.GetString("PreviewDownButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L (Left Shoulder).
        /// </summary>
        internal static string PreviewLButton {
            get {
                return ResourceManager.GetString("PreviewLButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left (&quot;Previous Track&quot;).
        /// </summary>
        internal static string PreviewLeftButton {
            get {
                return ResourceManager.GetString("PreviewLeftButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P Button (&quot;Play/Pause&quot;).
        /// </summary>
        internal static string PreviewPButton {
            get {
                return ResourceManager.GetString("PreviewPButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R (Right Shoulder).
        /// </summary>
        internal static string PreviewRButton {
            get {
                return ResourceManager.GetString("PreviewRButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right (&quot;Next Track&quot;).
        /// </summary>
        internal static string PreviewRightButton {
            get {
                return ResourceManager.GetString("PreviewRightButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up (&quot;Seek Forward&quot;).
        /// </summary>
        internal static string PreviewUpButton {
            get {
                return ResourceManager.GetString("PreviewUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Button (&quot;Stop&quot;).
        /// </summary>
        internal static string PreviewXButton {
            get {
                return ResourceManager.GetString("PreviewXButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set All.
        /// </summary>
        internal static string SetAll {
            get {
                return ResourceManager.GetString("SetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Input Settings.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
