//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourDO.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FourDO.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        internal static string BrowserColumnBytes {
            get {
                return ResourceManager.GetString("BrowserColumnBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        internal static string BrowserColumnExtension {
            get {
                return ResourceManager.GetString("BrowserColumnExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string BrowserColumnID {
            get {
                return ResourceManager.GetString("BrowserColumnID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string BrowserColumnName {
            get {
                return ResourceManager.GetString("BrowserColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Extract To....
        /// </summary>
        internal static string BrowserMenuExtract {
            get {
                return ResourceManager.GetString("BrowserMenuExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract &amp;Current Directory To....
        /// </summary>
        internal static string BrowserMenuExtractDirectory {
            get {
                return ResourceManager.GetString("BrowserMenuExtractDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Whole &amp;Disc To....
        /// </summary>
        internal static string BrowserMenuExtractDisc {
            get {
                return ResourceManager.GetString("BrowserMenuExtractDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open Directory.
        /// </summary>
        internal static string BrowserMenuOpenDirectory {
            get {
                return ResourceManager.GetString("BrowserMenuOpenDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Up.
        /// </summary>
        internal static string BrowserUp {
            get {
                return ResourceManager.GetString("BrowserUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc Browser.
        /// </summary>
        internal static string BrowserWindowTitle {
            get {
                return ResourceManager.GetString("BrowserWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3DOPlay Authors:.
        /// </summary>
        internal static string HelpAbout3DOPlayAuthors {
            get {
                return ResourceManager.GetString("HelpAbout3DOPlayAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In February of 2012, the core emulation from 3DOPlay was merged into 4DO&apos;s copy of the FreeDO core by Viktor, providing the benefit of two separate 3DO emulation projects!.
        /// </summary>
        internal static string HelpAbout3DOPlayMessage {
            get {
                return ResourceManager.GetString("HelpAbout3DOPlayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4DO Authors:.
        /// </summary>
        internal static string HelpAbout4DOAuthors {
            get {
                return ResourceManager.GetString("HelpAbout4DOAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4DO (FourDO) is an open-source, low-level emulator of the 3DO Interactive Multiplayer system..
        /// </summary>
        internal static string HelpAbout4DOMessage {
            get {
                return ResourceManager.GetString("HelpAbout4DOMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4DO Version:.
        /// </summary>
        internal static string HelpAbout4DOVersion {
            get {
                return ResourceManager.GetString("HelpAbout4DOVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string HelpAboutClose {
            get {
                return ResourceManager.GetString("HelpAboutClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeDO Authors:.
        /// </summary>
        internal static string HelpAboutFreeDOAuthors {
            get {
                return ResourceManager.GetString("HelpAboutFreeDOAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4DO&apos;s (and 3DOPlay&apos;s) system emulation is based on the code released from the FreeDO project that went open source on Nov 10, 2010.  Many thanks to the developers for deciding to release their code!.
        /// </summary>
        internal static string HelpAboutFreeDOMessage {
            get {
                return ResourceManager.GetString("HelpAboutFreeDOMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional thanks to:.
        /// </summary>
        internal static string HelpAboutJohnnyThank {
            get {
                return ResourceManager.GetString("HelpAboutJohnnyThank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Johnny would like to thank other folks, some of whom helped with the original, high-level approach..
        /// </summary>
        internal static string HelpAboutJohnnyThankMessage {
            get {
                return ResourceManager.GetString("HelpAboutJohnnyThankMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector 0+1 Checksum:.
        /// </summary>
        internal static string HelpInfoChecksum {
            get {
                return ResourceManager.GetString("HelpInfoChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Id:.
        /// </summary>
        internal static string HelpInfoGameId {
            get {
                return ResourceManager.GetString("HelpInfoGameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Name:.
        /// </summary>
        internal static string HelpInfoGameName {
            get {
                return ResourceManager.GetString("HelpInfoGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string HelpInfoOK {
            get {
                return ResourceManager.GetString("HelpInfoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher:.
        /// </summary>
        internal static string HelpInfoPublisher {
            get {
                return ResourceManager.GetString("HelpInfoPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region(s):.
        /// </summary>
        internal static string HelpInfoRegion {
            get {
                return ResourceManager.GetString("HelpInfoRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Year:.
        /// </summary>
        internal static string HelpInfoReleaseYear {
            get {
                return ResourceManager.GetString("HelpInfoReleaseYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Information.
        /// </summary>
        internal static string HelpInfoWindowTitle {
            get {
                return ResourceManager.GetString("HelpInfoWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bios file ({0}) failed to load. Please choose another..
        /// </summary>
        internal static string MainErrorLoadBiosFile {
            get {
                return ResourceManager.GetString("MainErrorLoadBiosFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game failed to load. Please choose another..
        /// </summary>
        internal static string MainErrorLoadGame {
            get {
                return ResourceManager.GetString("MainErrorLoadGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game file ({0}) failed to load. Please choose another..
        /// </summary>
        internal static string MainErrorLoadGameFile {
            get {
                return ResourceManager.GetString("MainErrorLoadGameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The nvram file ({0}) could not be loaded. Emulation cannot start.&quot;.
        /// </summary>
        internal static string MainErrorLoadNvramFile {
            get {
                return ResourceManager.GetString("MainErrorLoadNvramFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Audio.
        /// </summary>
        internal static string MainMenuAudio {
            get {
                return ResourceManager.GetString("MainMenuAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Console.
        /// </summary>
        internal static string MainMenuConsole {
            get {
                return ResourceManager.GetString("MainMenuConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Advance by a Single Frame.
        /// </summary>
        internal static string MainMenuConsoleAdvanceFrame {
            get {
                return ResourceManager.GetString("MainMenuConsoleAdvanceFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After Game is Opened, L&amp;oad Last Save (of Slot).
        /// </summary>
        internal static string MainMenuConsoleAutoLoadLastSave {
            get {
                return ResourceManager.GetString("MainMenuConsoleAutoLoadLastSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Load State.
        /// </summary>
        internal static string MainMenuConsoleLoadState {
            get {
                return ResourceManager.GetString("MainMenuConsoleLoadState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Pause.
        /// </summary>
        internal static string MainMenuConsolePause {
            get {
                return ResourceManager.GetString("MainMenuConsolePause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reset.
        /// </summary>
        internal static string MainMenuConsoleReset {
            get {
                return ResourceManager.GetString("MainMenuConsoleReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save State.
        /// </summary>
        internal static string MainMenuConsoleSaveState {
            get {
                return ResourceManager.GetString("MainMenuConsoleSaveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save State Slo&amp;t.
        /// </summary>
        internal static string MainMenuConsoleSaveStateSlot {
            get {
                return ResourceManager.GetString("MainMenuConsoleSaveStateSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;Next Slot.
        /// </summary>
        internal static string MainMenuConsoleSaveStateSlotNext {
            get {
                return ResourceManager.GetString("MainMenuConsoleSaveStateSlotNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;Previous Slot.
        /// </summary>
        internal static string MainMenuConsoleSaveStateSlotPrevious {
            get {
                return ResourceManager.GetString("MainMenuConsoleSaveStateSlotPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screens&amp;hot.
        /// </summary>
        internal static string MainMenuConsoleScreenshot {
            get {
                return ResourceManager.GetString("MainMenuConsoleScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Display.
        /// </summary>
        internal static string MainMenuDisplay {
            get {
                return ResourceManager.GetString("MainMenuDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-&amp;Crop Blank Borders.
        /// </summary>
        internal static string MainMenuDisplayAutoCrop {
            get {
                return ResourceManager.GetString("MainMenuDisplayAutoCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Full Screen.
        /// </summary>
        internal static string MainMenuDisplayFullscreen {
            get {
                return ResourceManager.GetString("MainMenuDisplayFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserve Aspect &amp;Ratio.
        /// </summary>
        internal static string MainMenuDisplayPreserveRatio {
            get {
                return ResourceManager.GetString("MainMenuDisplayPreserveRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap &amp;Window to Clean Increments.
        /// </summary>
        internal static string MainMenuDisplayResizeSnap {
            get {
                return ResourceManager.GetString("MainMenuDisplayResizeSnap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaling Mode.
        /// </summary>
        internal static string MainMenuDisplayScaling {
            get {
                return ResourceManager.GetString("MainMenuDisplayScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Resolution Rendering.
        /// </summary>
        internal static string MainMenuDisplayScalingDoubleRes {
            get {
                return ResourceManager.GetString("MainMenuDisplayScalingDoubleRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hq2x.
        /// </summary>
        internal static string MainMenuDisplayScalingHq2x {
            get {
                return ResourceManager.GetString("MainMenuDisplayScalingHq2x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hq3x.
        /// </summary>
        internal static string MainMenuDisplayScalingHq3x {
            get {
                return ResourceManager.GetString("MainMenuDisplayScalingHq3x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hq4x.
        /// </summary>
        internal static string MainMenuDisplayScalingHq4x {
            get {
                return ResourceManager.GetString("MainMenuDisplayScalingHq4x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string MainMenuDisplayScalingNone {
            get {
                return ResourceManager.GetString("MainMenuDisplayScalingNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Smooth Image Resizing.
        /// </summary>
        internal static string MainMenuDisplaySmoothResizing {
            get {
                return ResourceManager.GetString("MainMenuDisplaySmoothResizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank (Void) Area.
        /// </summary>
        internal static string MainMenuDisplayVoidArea {
            get {
                return ResourceManager.GetString("MainMenuDisplayVoidArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Gray Border.
        /// </summary>
        internal static string MainMenuDisplayVoidAreaDrawBorder {
            get {
                return ResourceManager.GetString("MainMenuDisplayVoidAreaDrawBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern : 4DO.
        /// </summary>
        internal static string MainMenuDisplayVoidAreaPattern4DO {
            get {
                return ResourceManager.GetString("MainMenuDisplayVoidAreaPattern4DO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern : Bumps.
        /// </summary>
        internal static string MainMenuDisplayVoidAreaPatternBumps {
            get {
                return ResourceManager.GetString("MainMenuDisplayVoidAreaPatternBumps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern : Metal.
        /// </summary>
        internal static string MainMenuDisplayVoidAreaPatternMetal {
            get {
                return ResourceManager.GetString("MainMenuDisplayVoidAreaPatternMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Pattern.
        /// </summary>
        internal static string MainMenuDisplayVoidAreaPatternNone {
            get {
                return ResourceManager.GetString("MainMenuDisplayVoidAreaPatternNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string MainMenuFile {
            get {
                return ResourceManager.GetString("MainMenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After Startup, Open Last Game.
        /// </summary>
        internal static string MainMenuFileAutoLoadLastGame {
            get {
                return ResourceManager.GetString("MainMenuFileAutoLoadLastGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose &amp;BIOS Rom (Current: {0})....
        /// </summary>
        internal static string MainMenuFileChooseBiosRom1 {
            get {
                return ResourceManager.GetString("MainMenuFileChooseBiosRom1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose BIOS Rom 2 : Kanji Font (Current: {0})....
        /// </summary>
        internal static string MainMenuFileChooseBiosRom2 {
            get {
                return ResourceManager.GetString("MainMenuFileChooseBiosRom2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close Game.
        /// </summary>
        internal static string MainMenuFileCloseRom {
            get {
                return ResourceManager.GetString("MainMenuFileCloseRom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string MainMenuFileExit {
            get {
                return ResourceManager.GetString("MainMenuFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Disc Drive.
        /// </summary>
        internal static string MainMenuFileOpenCDDrive {
            get {
                return ResourceManager.GetString("MainMenuFileOpenCDDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open CD &amp;Image CoreFile....
        /// </summary>
        internal static string MainMenuFileOpenCDImage {
            get {
                return ResourceManager.GetString("MainMenuFileOpenCDImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string MainMenuHelp {
            get {
                return ResourceManager.GetString("MainMenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About 4DO....
        /// </summary>
        internal static string MainMenuHelpAbout {
            get {
                return ResourceManager.GetString("MainMenuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game &amp;Information....
        /// </summary>
        internal static string MainMenuHelpGameInfo {
            get {
                return ResourceManager.GetString("MainMenuHelpGameInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options.
        /// </summary>
        internal static string MainMenuOptions {
            get {
                return ResourceManager.GetString("MainMenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure &amp;Input....
        /// </summary>
        internal static string MainMenuOptionsConfigureInput {
            get {
                return ResourceManager.GetString("MainMenuOptionsConfigureInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Language.
        /// </summary>
        internal static string MainMenuOptionsLanguage {
            get {
                return ResourceManager.GetString("MainMenuOptionsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Chinese - Simplified.
        /// </summary>
        internal static string MainMenuOptionsLanguageChinese {
            get {
                return ResourceManager.GetString("MainMenuOptionsLanguageChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System &amp;Default.
        /// </summary>
        internal static string MainMenuOptionsLanguageDefault {
            get {
                return ResourceManager.GetString("MainMenuOptionsLanguageDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;English.
        /// </summary>
        internal static string MainMenuOptionsLanguageEnglish {
            get {
                return ResourceManager.GetString("MainMenuOptionsLanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;French.
        /// </summary>
        internal static string MainMenuOptionsLanguageFrench {
            get {
                return ResourceManager.GetString("MainMenuOptionsLanguageFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;German.
        /// </summary>
        internal static string MainMenuOptionsLanguageGerman {
            get {
                return ResourceManager.GetString("MainMenuOptionsLanguageGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Portuguese.
        /// </summary>
        internal static string MainMenuOptionsLanguagePortuguese {
            get {
                return ResourceManager.GetString("MainMenuOptionsLanguagePortuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Russian.
        /// </summary>
        internal static string MainMenuOptionsLanguageRussian {
            get {
                return ResourceManager.GetString("MainMenuOptionsLanguageRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Spanish.
        /// </summary>
        internal static string MainMenuOptionsLanguageSpanish {
            get {
                return ResourceManager.GetString("MainMenuOptionsLanguageSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4DO &amp;Settings....
        /// </summary>
        internal static string MainMenuOptionsSettings {
            get {
                return ResourceManager.GetString("MainMenuOptionsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        internal static string MainMenuTools {
            get {
                return ResourceManager.GetString("MainMenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc &amp;Browser.
        /// </summary>
        internal static string MainMenuToolsDiscBrowser {
            get {
                return ResourceManager.GetString("MainMenuToolsDiscBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        internal static string MainMessageAllFiles {
            get {
                return ResourceManager.GetString("MainMessageAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIOS files.
        /// </summary>
        internal static string MainMessageBiosFiles {
            get {
                return ResourceManager.GetString("MainMessageBiosFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD image files.
        /// </summary>
        internal static string MainMessageCDImageFiles {
            get {
                return ResourceManager.GetString("MainMessageCDImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose BIOS Rom.
        /// </summary>
        internal static string MainMessageChooseBiosRom {
            get {
                return ResourceManager.GetString("MainMessageChooseBiosRom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core FPS.
        /// </summary>
        internal static string MainMessageCoreFPS {
            get {
                return ResourceManager.GetString("MainMessageCoreFPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Options.
        /// </summary>
        internal static string MainMessageDisplayOptions {
            get {
                return ResourceManager.GetString("MainMessageDisplayOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health:.
        /// </summary>
        internal static string MainMessageHealth {
            get {
                return ResourceManager.GetString("MainMessageHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string MainMessageHide {
            get {
                return ResourceManager.GetString("MainMessageHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No BIOS rom selected..
        /// </summary>
        internal static string MainMessageNoBiosSelected {
            get {
                return ResourceManager.GetString("MainMessageNoBiosSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot.
        /// </summary>
        internal static string MainMessageSlot {
            get {
                return ResourceManager.GetString("MainMessageSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown game.
        /// </summary>
        internal static string MainMessageUnknownGame {
            get {
                return ResourceManager.GetString("MainMessageUnknownGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string MainMessageVolume {
            get {
                return ResourceManager.GetString("MainMessageVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string SettingsCancel {
            get {
                return ResourceManager.GetString("SettingsCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string SettingsOK {
            get {
                return ResourceManager.GetString("SettingsOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string SettingsTabAdvanced {
            get {
                return ResourceManager.GetString("SettingsTabAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fewer Glitches.
        /// </summary>
        internal static string SettingsTabAdvancedAudioBufferFewerGlitches {
            get {
                return ResourceManager.GetString("SettingsTabAdvancedAudioBufferFewerGlitches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Buffer Size.
        /// </summary>
        internal static string SettingsTabAdvancedAudioBufferFrame {
            get {
                return ResourceManager.GetString("SettingsTabAdvancedAudioBufferFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Lag.
        /// </summary>
        internal static string SettingsTabAdvancedAudioBufferLessLag {
            get {
                return ResourceManager.GetString("SettingsTabAdvancedAudioBufferLessLag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The audio buffer provides tolerance for unpredictable emulation speed at the cost of audio delay. However, whenever emulation is terminally behind schedule, audio glitches will occur (even with large buffers)..
        /// </summary>
        internal static string SettingsTabAdvancedAudioBufferMessage {
            get {
                return ResourceManager.GetString("SettingsTabAdvancedAudioBufferMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MORE Glitches.
        /// </summary>
        internal static string SettingsTabAdvancedAudioBufferMoreGlitches {
            get {
                return ResourceManager.GetString("SettingsTabAdvancedAudioBufferMoreGlitches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MORE Lag.
        /// </summary>
        internal static string SettingsTabAdvancedAudioBufferMoreLag {
            get {
                return ResourceManager.GetString("SettingsTabAdvancedAudioBufferMoreLag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Clock Speed.
        /// </summary>
        internal static string SettingsTabAdvancedClockFrame {
            get {
                return ResourceManager.GetString("SettingsTabAdvancedClockFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higher FPS.
        /// </summary>
        internal static string SettingsTabAdvancedClockHigherFPS {
            get {
                return ResourceManager.GetString("SettingsTabAdvancedClockHigherFPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By adjusting the CPU clock speed, you can potentially achieve higher FPS in games. Not all games will handle this appropriately. Games dependent on precise timing could even crash/freeze..
        /// </summary>
        internal static string SettingsTabAdvancedClockMessage {
            get {
                return ResourceManager.GetString("SettingsTabAdvancedClockMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal FPS.
        /// </summary>
        internal static string SettingsTabAdvancedClockNormalFPS {
            get {
                return ResourceManager.GetString("SettingsTabAdvancedClockNormalFPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider setting these to defaults if seeing odd behavior..
        /// </summary>
        internal static string SettingsTabAdvancedDefaultsMessage {
            get {
                return ResourceManager.GetString("SettingsTabAdvancedDefaultsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-Resolution Rendering.
        /// </summary>
        internal static string SettingsTabAdvancedHighResFrame {
            get {
                return ResourceManager.GetString("SettingsTabAdvancedHighResFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Via software rendering, the screen images can be rendered to 640 x 480. This is very CPU intensive, and only of value to 3D games! If using this option, consider increasing audio buffer size as well..
        /// </summary>
        internal static string SettingsTabAdvancedHighResMessage {
            get {
                return ResourceManager.GetString("SettingsTabAdvancedHighResMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable high-resolution video rendering.
        /// </summary>
        internal static string SettingsTabAdvancedHighResSetting {
            get {
                return ResourceManager.GetString("SettingsTabAdvancedHighResSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to defaults.
        /// </summary>
        internal static string SettingsTabAdvancedResetDefaults {
            get {
                return ResourceManager.GetString("SettingsTabAdvancedResetDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string SettingsTabDisplay {
            get {
                return ResourceManager.GetString("SettingsTabDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically crop game area to remove black borders.
        /// </summary>
        internal static string SettingsTabDisplayAutoCrop {
            get {
                return ResourceManager.GetString("SettingsTabDisplayAutoCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw gray border around viewing area.
        /// </summary>
        internal static string SettingsTabDisplayDrawBorder {
            get {
                return ResourceManager.GetString("SettingsTabDisplayDrawBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;General Display Settings.
        /// </summary>
        internal static string SettingsTabDisplayGeneralOptions {
            get {
                return ResourceManager.GetString("SettingsTabDisplayGeneralOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preserve aspect ratio.
        /// </summary>
        internal static string SettingsTabDisplayPreserveAspectRatio {
            get {
                return ResourceManager.GetString("SettingsTabDisplayPreserveAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Resolution Rendering.
        /// </summary>
        internal static string SettingsTabDisplayScalingModeDoubleRes {
            get {
                return ResourceManager.GetString("SettingsTabDisplayScalingModeDoubleRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Via software rendering, the screen images can be rendered to 640 x 480. This is only of value to 3D Games..
        /// </summary>
        internal static string SettingsTabDisplayScalingModeDoubleResMessage {
            get {
                return ResourceManager.GetString("SettingsTabDisplayScalingModeDoubleResMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaling Mode.
        /// </summary>
        internal static string SettingsTabDisplayScalingModeFrame {
            get {
                return ResourceManager.GetString("SettingsTabDisplayScalingModeFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hq2x.
        /// </summary>
        internal static string SettingsTabDisplayScalingModeHq2x {
            get {
                return ResourceManager.GetString("SettingsTabDisplayScalingModeHq2x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hq3x.
        /// </summary>
        internal static string SettingsTabDisplayScalingModeHq3x {
            get {
                return ResourceManager.GetString("SettingsTabDisplayScalingModeHq3x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hq4x.
        /// </summary>
        internal static string SettingsTabDisplayScalingModeHq4x {
            get {
                return ResourceManager.GetString("SettingsTabDisplayScalingModeHq4x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;hqx&quot; is a post-processing filter that attempts to enhance the image by matching adjacent colors..
        /// </summary>
        internal static string SettingsTabDisplayScalingModeHqxMessage {
            get {
                return ResourceManager.GetString("SettingsTabDisplayScalingModeHqxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The console&apos;s image is typically rendered as 320x240. If using any of the scaling options, consider adjusting the CPU clock speed or the audio buffer size (in the &quot;Advanced&quot; tab)..
        /// </summary>
        internal static string SettingsTabDisplayScalingModeMessage {
            get {
                return ResourceManager.GetString("SettingsTabDisplayScalingModeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Scaling.
        /// </summary>
        internal static string SettingsTabDisplayScalingModeNone {
            get {
                return ResourceManager.GetString("SettingsTabDisplayScalingModeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Scaling modes are CPU intensive!.
        /// </summary>
        internal static string SettingsTabDisplayScalingModeWarning {
            get {
                return ResourceManager.GetString("SettingsTabDisplayScalingModeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform smooth image resizing.
        /// </summary>
        internal static string SettingsTabDisplaySmoothResizing {
            get {
                return ResourceManager.GetString("SettingsTabDisplaySmoothResizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When resizing the window, snap to clean increments.
        /// </summary>
        internal static string SettingsTabDisplaySnapResizing {
            get {
                return ResourceManager.GetString("SettingsTabDisplaySnapResizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank (&amp;Void) Area Effects.
        /// </summary>
        internal static string SettingsTabDisplayVoidOptions {
            get {
                return ResourceManager.GetString("SettingsTabDisplayVoidOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background pattern:.
        /// </summary>
        internal static string SettingsTabDisplayVoidPattern {
            get {
                return ResourceManager.GetString("SettingsTabDisplayVoidPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4DO.
        /// </summary>
        internal static string SettingsTabDisplayVoidPattern4DO {
            get {
                return ResourceManager.GetString("SettingsTabDisplayVoidPattern4DO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bumps.
        /// </summary>
        internal static string SettingsTabDisplayVoidPatternBumps {
            get {
                return ResourceManager.GetString("SettingsTabDisplayVoidPatternBumps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metal.
        /// </summary>
        internal static string SettingsTabDisplayVoidPatternMetal {
            get {
                return ResourceManager.GetString("SettingsTabDisplayVoidPatternMetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pattern.
        /// </summary>
        internal static string SettingsTabDisplayVoidPatternNone {
            get {
                return ResourceManager.GetString("SettingsTabDisplayVoidPatternNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string SettingsTabGeneral {
            get {
                return ResourceManager.GetString("SettingsTabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When 4DO starts, open whatever game was running last time.
        /// </summary>
        internal static string SettingsTabGeneralAutoLoadLastGame {
            get {
                return ResourceManager.GetString("SettingsTabGeneralAutoLoadLastGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a game is opened, re-load the last save state of the current save state slot.
        /// </summary>
        internal static string SettingsTabGeneralAutoLoadLastSave {
            get {
                return ResourceManager.GetString("SettingsTabGeneralAutoLoadLastSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Various &amp;Behaviorial Options.
        /// </summary>
        internal static string SettingsTabGeneralBehaviorOptions {
            get {
                return ResourceManager.GetString("SettingsTabGeneralBehaviorOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the main window loses focus, ignore keyboard input.
        /// </summary>
        internal static string SettingsTabGeneralInactiveIgnoreKeyboard {
            get {
                return ResourceManager.GetString("SettingsTabGeneralInactiveIgnoreKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Inactive Window Options.
        /// </summary>
        internal static string SettingsTabGeneralInactiveOptions {
            get {
                return ResourceManager.GetString("SettingsTabGeneralInactiveOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the main window loses focus, pause emulation.
        /// </summary>
        internal static string SettingsTabGeneralInactivePauseEmulation {
            get {
                return ResourceManager.GetString("SettingsTabGeneralInactivePauseEmulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Startup Options.
        /// </summary>
        internal static string SettingsTabGeneralStartupOptions {
            get {
                return ResourceManager.GetString("SettingsTabGeneralStartupOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure various 4DO settings.
        /// </summary>
        internal static string SettingsWindowInstructions {
            get {
                return ResourceManager.GetString("SettingsWindowInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }
    }
}
